src/App/Controllers/AdminController.cs
using Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace App.Controllers
{
    [Authorize]
    [ApiExplorerSettings(IgnoreApi = true)]
    public class AdminController : Controller
    {
        IDataService _db;
        IImportService _feed;

        public AdminController(IDataService db, IImportService feed)
        {
            _db = db;
            _feed = feed;
        }

        public IActionResult Index()
        {
            return Redirect("~/admin/posts");
        }

        [HttpPost, Route("[controller]/importfeed")]
        public async Task<IEnumerable<ImportMessage>> ImportFeed(IFormFile file)
        {
            var author = _db.Authors.Single(a => a.AppUserName == User.Identity.Name);

            if(!author.IsAdmin)
                Redirect("~/pages/shared/_error/403");

            var webRoot = Url.Content("~/");

            return await _feed.Import(file, User.Identity.Name, webRoot);
        }

        [HttpDelete, Route("[controller]/notifications/remove/{id}")]
        public async Task RemoveNotification(int id)
        {
            var note = _db.Notifications.Single(n => n.Id == id);
            _db.Notifications.Remove(note);
            _db.Complete();
            await Task.CompletedTask;
        }
    }
}

src/App/Controllers/BlogController.cs
using Core.Data;
using Core.Helpers;
using Core.Services;
using Markdig;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;

namespace App.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    public class BlogController : Controller
    {
        IDataService _db;
        IFeedService _ss;
        SignInManager<AppUser> _sm;
        private readonly ICompositeViewEngine _viewEngine;
        static readonly string _listView = "~/Views/Themes/{0}/List.cshtml";

        public BlogController(IDataService db, IFeedService ss, SignInManager<AppUser> sm, ICompositeViewEngine viewEngine)
        {
            _db = db;
            _ss = ss;
            _sm = sm;
            _viewEngine = viewEngine;
        }

        public async Task<IActionResult> Index(int page = 1, string term = "")
        {
            var blog = await _db.CustomFields.GetBlogSettings();
            var pager = new Pager(page, blog.ItemsPerPage);
            IEnumerable<PostItem> posts;

            if (string.IsNullOrEmpty(term))
            {
                posts = await _db.BlogPosts.GetList(p => p.Published > DateTime.MinValue, pager);
            }
            else
            {
                posts = await _db.BlogPosts.Search(pager, term);
            }

            if (pager.ShowOlder) pager.LinkToOlder = $"blog?page={pager.Older}";
            if (pager.ShowNewer) pager.LinkToNewer = $"blog?page={pager.Newer}";

            var model = new ListModel {
                Blog = blog,
                PostListType = PostListType.Blog,
                Posts = posts,
                Pager = pager
            };

            if (!string.IsNullOrEmpty(term))
            {
                model.Blog.Title = term;
                model.Blog.Description = "";
                model.PostListType = PostListType.Search;
            }

            model.Blog.Cover = $"{Url.Content("~/")}{model.Blog.Cover}";

            return View(string.Format(_listView, blog.Theme), model);
        }

        [HttpGet("posts/{slug}")]
        public async Task<IActionResult> Single(string slug)
        {
            try
            {
                var model = await _db.BlogPosts.GetModel(slug);
                model.Post.Content = Markdown.ToHtml(model.Post.Content);

                model.Blog = await _db.CustomFields.GetBlogSettings();

                model.Blog.Cover = string.IsNullOrEmpty(model.Post.Cover) ? 
                    $"{Url.Content("~/")}{model.Blog.Cover}" : 
                    $"{Url.Content("~/")}{model.Post.Cover}";
                model.Blog.Title = model.Post.Title;

                return View($"~/Views/Themes/{model.Blog.Theme}/Post.cshtml", model);
            }
            catch
            {
                return Redirect("~/error/404");
            }
            
        }

        [HttpGet("authors/{name}")]
        public async Task<IActionResult> Authors(string name, int page = 1)
        {
            var blog = await _db.CustomFields.GetBlogSettings();
            var author = await _db.Authors.GetItem(a => a.AppUserName == name);

            var pager = new Pager(page, blog.ItemsPerPage);
            var posts = await _db.BlogPosts.GetList(p => p.Published > DateTime.MinValue && p.AuthorId == author.Id, pager);

            if (pager.ShowOlder) pager.LinkToOlder = $"authors/{name}?page={pager.Older}";
            if (pager.ShowNewer) pager.LinkToNewer = $"authors/{name}?page={pager.Newer}";

            var model = new ListModel {
                PostListType = PostListType.Author,
                Author = author,
                Posts = posts,
                Pager = pager
            };

            model.Blog = blog;
            model.Blog.Cover = $"{Url.Content("~/")}{model.Blog.Cover}";
            model.Blog.Description = "";

            return View(string.Format(_listView, model.Blog.Theme), model);
        }

        [HttpGet("categories/{name}")]
        public async Task<IActionResult> Categories(string name, int page = 1)
        {
            var blog = await _db.CustomFields.GetBlogSettings();
            var pager = new Pager(page, blog.ItemsPerPage);
            var posts = await _db.BlogPosts.GetList(pager, 0, name);

            if (pager.ShowOlder) pager.LinkToOlder = $"categories/{name}?page={pager.Older}";
            if (pager.ShowNewer) pager.LinkToNewer = $"categories/{name}?page={pager.Newer}";

            var model = new ListModel
            {
                PostListType = PostListType.Category,
                Posts = posts,
                Pager = pager
            };

            model.Blog = blog;
            model.Blog.Cover = $"{Url.Content("~/")}{model.Blog.Cover}";

            ViewBag.Category = name;
            model.Blog.Description = "";

            return View(string.Format(_listView, model.Blog.Theme), model);
        }

        [HttpGet("feed/{type}")]
        public async Task Rss(string type)
        {
            Response.ContentType = "application/xml";
            string host = Request.Scheme + "://" + Request.Host;

            using (XmlWriter xmlWriter = XmlWriter.Create(Response.Body, new XmlWriterSettings() { Async = true, Indent = true }))
            {
                var posts = await _ss.GetEntries(type, host);

                if (posts != null && posts.Count() > 0)
                {
                    var lastUpdated = posts.FirstOrDefault().Published;
                    var writer = await _ss.GetWriter(type, host, xmlWriter);

                    foreach (var post in posts)
                    {
                        post.Description = Markdown.ToHtml(post.Description);
                        await writer.Write(post);
                    }
                }
            }
        }

        [HttpGet("error/{code:int}")]
        public async Task<IActionResult> Error(int code)
        {
            var model = new PostModel();

            model.Blog = await _db.CustomFields.GetBlogSettings();
            model.Blog.Cover = $"{Url.Content("~/")}{model.Blog.Cover}";

            var viewName = $"~/Views/Themes/{model.Blog.Theme}/Error.cshtml";
            var result = _viewEngine.GetView("", viewName, false);

            if (result.Success)
            {
                return View(viewName, model);
            }
            else
            {
                return View("~/Views/Shared/_Error.cshtml", model);
            }
        }

        [HttpPost, Route("account/logout")]
        public async Task<IActionResult> Logout()
        {
            await _sm.SignOutAsync();
            return Redirect("~/");
        }
    }
}

src/App/Pages/Admin/Shared/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;

namespace App.Pages.Admin.Shared
{
    public class ErrorModel : AdminPageModel
    {
        [BindProperty]
        public int Code { get; set; }

        public void OnGet(int code)
        {
            Code = code;
        }
    }
}

src/App/Views/Themes/spot/_Shared/_Footer.cshtml
@{
    var returnUrl = Url.Action("Index", "Admin");
}
<footer class="blog-footer">
    <div class="container">
        <div class="blog-copyright">
            <a href="~/" class="blog-logo d-block"> <img src="~/themes/spot/img/logo-white.png" alt="@Model.Blog.Title" /></a>

            <p class="">Copyright © @DateTime.Now.Year. Powered by <a href="https://github.com/dejvi_zyberi_blogger" data-toggle="tooltip" target="_blank" title="Version - @AppSettings.Version">Blogger</a>. Designed by <a href="https://dejvizyberi.bio/" target="_blank" rel="nofollow">Dejvi</a>.</p>
        </div>
        @*@await Component.InvokeAsync("HtmlBlock", new { theme = "bridge", widget = "Social Buttons" })*@
        <ul class=" list-unstyled">
            @if (User.Identity.IsAuthenticated)
            {
            <li>
                <a href="~/admin"><i class="fa fa-user"></i></a>
            </li>
            }
            else
            {
            <li>
                <a href="~/account/login?ReturnUrl=@returnUrl"><i class="fa fa-login"></i></a>
            </li>
            }
        </ul>
    </div>
</footer>

@*<a href="#" onclick="profileLogOut(); return false;">Logoff</a>
    <form method="post" id="frmLogOut" asp-controller="Account" asp-action="Logout" asp-antiforgery="true"></form>*@
<script src="~/themes/spot/js/jquery.min.js"></script>
<script src="~/themes/spot/js/popper.min.js"></script>
<script src="~/themes/spot/js/bootstrap.min.js"></script>
<script src="~/themes/spot/js/prism.js"></script>
<script src="~/themes/spot/js/blog.js" asp-append-version="true"></script>

src/App/Views/Themes/spot/_Shared/_Head.cshtml
<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>@Html.Raw(Model.Blog.Title)</title>
<meta name="description" content="@Html.Raw(Model.Blog.Description)">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,500,400,700|Merriweather:700" rel="stylesheet">
<link href="~/themes/spot/css/bootstrap.min.css" rel="stylesheet">
<link href="~/themes/spot/css/font-awesome.min.css" rel="stylesheet">
<link href="~/themes/spot/css/prism.css" rel="stylesheet">
<link href="~/themes/spot/css/styles.min.css" rel="stylesheet" asp-append-version="true">
<link rel="shortcut icon" href="~/lib/img/favicon.ico">

src/App/Views/Themes/spot/_Shared/_Header.cshtml
<header class="blog-header">
    <div class="blog-nav">
        <div class="container d-flex">
            <nav class="navbar navbar-expand-lg navbar-dark mr-auto">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="~/">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link" href="~/admin">Admin</a>
                            }
                            else
                            {
                                <a class="nav-link" href="~/account/login?ReturnUrl=/admin">Login</a>
                            }
                        </li>
                    </ul>
                </div>
            </nav>
            <form class="blog-search-form my-auto" role="search" asp-controller="Blog" asp-action="Index" method="post">
                <input type="search" id="term" name="term" class="form-control" placeholder="Search..." autocomplete="off">
                <button type="submit"><i class="fa fa-search"></i></button>
            </form>
        </div>
    </div>
    <a href="~/" class="blog-logo d-block"> <img src="~/themes/spot/img/logo.png" alt="@Model.Blog.Title" /></a>
</header>